name: Docs

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pages-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@568ddd69406b30de1774ec0044b73ae06e716aa4 # v4
        with:
          cache: true
          python-version: '3.13'
          version: 2.15.2
      - run: env | sort
      - run: make dev-doc
      - run: make doc
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: public
  pages:
    needs:
      - pages-build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-22.04
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
