name: Release

on:
  release:
    types:
      - published

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  container-publish:
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - run: |
          docker context create builder
          docker buildx create builder --name container --driver docker-container --use
          docker buildx inspect --bootstrap --builder container
      - run: |
          docker buildx build . \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --cache-from type=registry,ref=ghcr.io/${{ github.repository }}/dev-cache:py${{ matrix.python-version }} \
            --cache-to type=registry,ref=ghcr.io/${{ github.repository }}/dev-cache:py${{ matrix.python-version }},mode=max \
            --file .devcontainer/Dockerfile \
            --provenance false \
            --push \
            --tag ghcr.io/${{ github.repository }}/dev:py${{ matrix.python-version }} \
            --tag ghcr.io/${{ github.repository }}/dev:py${{ matrix.python-version }}-${{ github.ref_name }} \
            --target dev
      - run: |
          docker buildx build . \
            --build-arg PDM_BUILD_SCM_VERSION=${{ github.ref_name }} \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --cache-from type=registry,ref=ghcr.io/${{ github.repository }}/dev-cache:py${{ matrix.python-version }} \
            --file .devcontainer/Dockerfile \
            --provenance false \
            --push \
            --tag ghcr.io/${{ github.repository }}:py${{ matrix.python-version }} \
            --tag ghcr.io/${{ github.repository }}:py${{ matrix.python-version }}-${{ github.ref_name }} \
            --target prod
    strategy:
      matrix:
        python-version:
          - '3.11'
  package-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: pdm-project/setup-pdm@568ddd69406b30de1774ec0044b73ae06e716aa4 # v4
        with:
          cache: true
          python-version: '3.11'
          version: 2.15.2
      - run: env | sort
      - env:
          PDM_PUBLISH_PASSWORD: ${{ secrets.PDM_PUBLISH_PASSWORD }}
          PDM_PUBLISH_USERNAME: ${{ vars.PDM_PUBLISH_USERNAME || '__token__' }}
        run: make publish
